version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: doublevpartners
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  docker run --name doublevpartnersDB-postgres -e POSTGRES_PASSWORD=doublevpartnersDB -p 5432:5432 -d postgres
  web:
    build: .
    command: npm start
    volumes:
      - .:/code
    ports:
      - "3000:3000"
    depends_on:
      - db
