# Use an official Node.js runtime as the parent image
FROM node:16

# Set the working directory in the container to /app
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install the application dependencies
RUN npm install

# Copy the rest of the application to the working directory
COPY . .

# Make port 3000 available to the world outside the container
EXPOSE 3000

# Run the application when the container launches
CMD ["npm", "start"]
