version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: doublevpartners
      MYSQL_DATABASE: doublevpartnersDB
      MYSQL_USER: test
      MYSQL_PASSWORD: doublevpartnersDB
volumes:
  db_data: {}
docker run --name doublevpartnersDB-postgres -e POSTGRES_PASSWORD=mysecretpassword -p 5432:5432 -d postgres
